### PR TITLE
Fix DirectWrite raster bounds

### LINKED ISSUE #15: DirectWrite glyph rasterization seem to be offset
The glyph rasterization using the DirectWrite loader seems to cut off the glyph on the right edge of the canvas. FreeType seems to work correctly but I run into the #14 issue and only the first glyph rasterized works.

Forcibly increasing the raster bound size in the render-glyph example seems to give the correct results.

Output of render-glyph example:
<details> 
  <summary>render-glyph (DirectWrite)</summary>

```
d:/projects/font-kit $ cargo run --example render-glyph -- "Calibri" "H" 24
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running `target\debug\examples\render-glyph.exe` Calibri H 24
glyph 44:
  ████              ██
  ████              ██
  ████              ██
  ████              ██
  ████              ██
  ████              ██
  ████████████████████
  ████████████████████
  ████              ██
  ████              ██
  ████              ██
  ████              ██
  ████              ██
  ████              ██
  ████              ██
                      
                      
d:/projects/font-kit $ cargo run --example render-glyph -- "Calibri" "e" 24
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `target\debug\examples\render-glyph.exe` Calibri e 24
glyph 286:
      ░░████████▒▒  
    ▒▒████████████▓▓
  ░░████        ▓▓██
  ▓▓██░░        ░░██
  ▓▓████████████████
  ▓▓████████████████
  ▓▓██░░            
  ▓▓██▒▒            
  ▒▒████▒▒        ██
    ▓▓██████████████
      ▒▒██████████░░
                    
```
</details>

<details> 
  <summary>render-glyph (FreeType)</summary>

```
d:/projects/font-kit $ cargo run --features loader-freetype-default --example render-glyph -- "Calibri" "e" 24
    Finished dev [unoptimized + debuginfo] target(s) in 5.50s
     Running `target\debug\examples\render-glyph.exe Calibri e 24`
glyph 286:
      ░░░░▒▒░░░░    
  ░░▒▒▓▓██████▓▓░░  
░░▓▓██▓▓░░░░▒▒▓▓▓▓░░
░░██▓▓        ▒▒██▒▒
▓▓██░░        ░░██▓▓
▓▓██▒▒▒▒▒▒▒▒▒▒▓▓██▓▓
▓▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒
▓▓██░░              
▓▓██▒▒              
▒▒██▓▓░░        ░░░░
░░▓▓██▓▓▒▒▒▒▒▒▒▒▓▓░░
  ░░▒▒▓▓██████▓▓▒▒░░
      ░░░░░░░░░░    
d:/projects/font-kit $ cargo run --features loader-freetype-default --example render-glyph -- "Calibri" "H" 24
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target\debug\examples\render-glyph.exe Calibri H 24`
glyph 44:
░░░░              ░░░░
▓▓██░░          ░░██▓▓
▓▓██░░          ░░██▓▓
▓▓██░░          ░░██▓▓
▓▓██░░          ░░██▓▓
▓▓██░░          ░░██▓▓
▓▓██░░          ░░██▓▓
▓▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▓██▓▓
▓▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▓██▓▓
▓▓██░░          ░░██▓▓
▓▓██░░          ░░██▓▓
▓▓██░░          ░░██▓▓
▓▓██░░          ░░██▓▓
▓▓██░░          ░░██▓▓
▓▓██░░          ░░██▓▓
▓▓▓▓░░          ░░▓▓▓▓
░░░░              ░░░░
```
</details>

<details> 
  <summary>render-glyph (DirectWrite) with bounds.size.x += 1</summary>

```
d:/projects/font-kit $ cargo run --example render-glyph -- "Calibri" "H" 24
   Compiling font-kit v0.1.0 (D:\projects\font-kit)
    Finished dev [unoptimized + debuginfo] target(s) in 1.70s
     Running `target\debug\examples\render-glyph.exe Calibri H 24`
glyph 44:
  ████              ████
  ████              ████
  ████              ████
  ████              ████
  ████              ████
  ████              ████
  ██████████████████████
  ██████████████████████
  ████              ████
  ████              ████
  ████              ████
  ████              ████
  ████              ████
  ████              ████
  ████              ████
                        
                        
d:/projects/font-kit $ cargo run --example render-glyph -- "Calibri" "e" 24
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target\debug\examples\render-glyph.exe Calibri e 24`
glyph 286:
      ░░████████▒▒    
    ▒▒████████████▓▓  
  ░░████        ▓▓██▒▒
  ▓▓██░░        ░░██▓▓
  ▓▓████████████████▓▓
  ▓▓████████████████▓▓
  ▓▓██░░              
  ▓▓██▒▒              
  ▒▒████▒▒        ██▒▒
    ▓▓██████████████▒▒
      ▒▒██████████░░  
                        
```
</details>

### PR DESCRIPTION
**Pull request by fkaa**
Fixes #15

### CODE REVIEW

File: src/loaders/directwrite.rs [hunk 1]
```diff
@@ -341,12 +341,24 @@ impl Font {
...
+            RasterizationOptions::GrayscaleAa | RasterizationOptions::SubpixelAa => {
+                DWRITE_TEXTURE_CLEARTYPE_3x1
+            }
+        };
+
+        let texture_bounds = dwrite_analysis.get_alpha_texture_bounds(texture_type);
+        let texture_width = texture_bounds.right - texture_bounds.left;
+        let texture_height = texture_bounds.bottom - texture_bounds.top;
+
+        Ok(Rect::new(Point2D::new(0, 0), Size2D::new(texture_width, texture_height).to_i32()))
```
Comment (zacps) [inline src/loaders/directwrite.rs]: The point should be `origin.round().cast::<i32>()`, which will matter when https://github.com/pcwalton/font-kit/pull/19 is merged.
